# https://atuin.sh/docs/config

auto_sync = false
update_check = false
search_mode = "fulltext"
style = "compact"
inline_height = 10
filter_mode = "directory"
show_help = false
history_filter = [
   "^jj",
]
