location:
  source_directories:
  - /home/croissong
  - /etc
  repositories:
  - /tmp/local.borg

  exclude_patterns:
    - '*.pyc'
    - '*/node_modules/'
    - '*/tmp/'
    - '*/scratch/'
    - '*/.git/modules/'
    - '*/.mypy_cache/'

  exclude_caches: true
  exclude_if_present:
    - .nobackup
  exclude_from:
    - /tmp/excludes.txt

hooks:
  before_backup:
    - /home/croissong/Dotfiles/dot_config/borgmatic/excludes.sh

retention:
    # Retention policy for how many backups to keep.
    keep_daily: 7
    keep_weekly: 4
    keep_monthly: 6
