# https://github.com/rossmacarthur/dotfiles/blob/trunk/src/sheldon/plugins.toml

shell = "zsh"

[templates]
defer = """{{ hooks | get: "pre" | nl }}{% for file in files %}zsh-defer source "{{ file }}"\n{% endfor %}{{ hooks | get: "post" | nl }}"""
defer-more = """{{ hooks | get: "pre" | nl }}{% for file in files %}zsh-defer -t 0.5 source "{{ file }}"\n{% endfor %}{{ hooks | get: "post" | nl }}"""


[plugins]

[plugins.starship]
inline = 'eval $(starship init zsh)'


[plugins.zsh-defer]
github = "romkatv/zsh-defer"


[plugins.direnv]
inline = 'zsh-defer -c "eval $(direnv hook zsh)"'

[plugins.atuin]
inline = """
zsh-defer -c 'eval "$(atuin init zsh --disable-up-arrow)"'
"""

[plugins.broot]
inline = 'zsh-defer source $XDG_CONFIG_HOME/broot/launcher/bash/br'

[plugins.enhancd]
github = "b4b4r07/enhancd"
apply = ["defer"]
hooks.pre = """
  ENHANCD_ENABLE_HOME=false
  ENHANCD_USE_ABBREV=true
  ENHANCD_FILTER="fzf --height 25%:fzy"
"""

[plugins.fzf-tab]
github = "Aloxaf/fzf-tab"
apply = ["defer"]
hooks.post = """
export FZF_DEFAULT_COMMAND='fd --type f'
zstyle ':fzf-tab:complete:cd:*' fzf-preview 'eza -1 --color=always $realpath'
zstyle ':completion:complete:*:options' sort false
"""

[plugins.zsh-syntax-highlighting]
github = "zdharma-continuum/fast-syntax-highlighting"
apply = ["defer"]

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"
apply = ["defer"]

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
use = ["{{ name }}.zsh"]
apply = ["defer"]

[plugins.kubeswitch]
local = "~/.nix-profile/share"
use = ["switch.zsh"]
apply = ["defer"]

[plugins.compinit]
github = "rossmacarthur/dotfiles"
use = ["src/zsh/plugins/compinit.plugin.zsh"]
apply = ["defer"]

[plugins.zoxide]
inline = 'zsh-defer -c "eval $(zoxide init --cmd c zsh)"'
