#!/usr/bin/env bash
###############################################################################
# .nbrc
#
# Configuration file for `nb`, a command line note-taking, bookmarking,
# and knowledge base application with encryption, search, Git-backed syncing,
# and more in a single portable script.
#
# Edit this file manually or manage settings using the `nb settings`
# subcommand. Configuration options are set as environment variables, eg:
#   export NB_ENCRYPTION_TOOL=gpg
#
# https://github.com/xwmx/nb
###############################################################################

export NB_DEFAULT_EXTENSION="${NB_DEFAULT_EXTENSION:-org}" # Set by `nb` • Di 9. Mär 08:32:22 CET 2021

export NB_SYNTAX_THEME="${NB_SYNTAX_THEME:-gruvbox-light}" # Set by `nb` • Di 9. Mär 08:55:28 CET 2021
