# pypi:
#   - package: cqlsh
#   - package: promformat
#   - package: xmlformatter


commitlint-rs:
  owner: KeisukeYamashita

desed:
  owner: SoptikHa2
  asset: desed-x86_64-unknown-linux-gnu


gitwatch:
  owner: gitwatch

focus:
  owner: ayoisaiah
  asset: focus_${VERSION}_linux_amd64.tar.gz

protocurl:
  owner: qaware
  asset: protocurl_${VERSION}_linux_amd64.zip

qsv:
  owner: jqnatividad
  trimPrefix: false
  asset: qsv-${VERSION}-x86_64-unknown-linux-gnu.zip

sane-scan-pdf:
  owner: rocketraman

sttr:
  owner: abhimanyu003
  asset: sttr_${VERSION}_linux_amd64.tar.gz

wutag:
  owner: vv9k
  asset: wutag-${VERSION}-x86_64-unknown-linux.tar.xz
  trimPrefix: false
