# ln -s $XDG_CONFIG_HOME/treefmt/treefmt.toml treefmt.toml
# ignore in .git/info/exclude

[formatter.nix]
command = "alejandra"
includes = ["*.nix"]

[formatter.shell]
command = "shfmt"
includes = ["*.sh"]

[formatter.xml]
command = "xmlformat"
options = ["--blanks", "--indent", "4", "--selfclose", "-"]
includes = ["*.xml"]
