[formatter.nix]
command = "alejandra"
includes = ["*.nix*"]

[formatter.shell]
includes = ["*.sh"]
command = "shfmt"
options = ["--write"]

[formatter.xml]
command = "xmlformat"
options = ["--blanks", "--indent", "4", "--selfclose", "-"]
includes = ["*.xml"]

[formatter.prettier]
includes = ["*.js", "*.ts", "*.html"]
command = "prettier"
options = ["--write"]


[formatter.jsonnet]
command = "jsonnetfmt"
options = ["--in-place"]
includes = ["*.jsonnet", "*.libsonnet"]

[formatter.go]
includes = ["*.go"]
command = "gofmt"
options = ["-w"]

[formatter.terraform]
includes = ["*.tf"]
command = "terraform"
options = ["fmt"]

[formatter.d2]
includes = ["*.d2"]
command = "d2"
options = ["fmt"]

[formatter.rust]
includes = ["*.rs"]
command = "rustfmt"

[formatter.slint]
includes = ["*.slint"]
command = "slint-fmt"
options = ["--inline"]
