apply:
    terraform apply -parallelism=1

get-rules:
  ./mgc login --scopes User.ReadWrite Mail.ReadWrite MailboxSettings.ReadWrite
  ./mgc users item mail-folders item message-rules list --user-id jm@datawerk.com --mail-folder-id inbox

trigger-rule:
  ./mgc users item mail-folders item message-rules item get --user-id jm@datawerk.com --mail-folder-id inbox --message-rule-id AgAABSMdbos= --output text
