apply:
  summon -f summon.yml \
  updatecli apply \
  --values dot/values.yaml \
  -c dot/nix.yaml

diff:
  summon -f summon.yml \
  updatecli diff \
  --values dot-values.yaml \
  -c nix.yaml


manifest:
  summon -f summon.yml \
  updatecli manifest show \
  --values dot-values.yaml \
  -c nix.yaml --clean


apply-wrk:
  summon -f summon.yml \
  updatecli apply \
  --values wrk/values.yaml \
  -c wrk
