# TODO?:
# set shell := ['nu', '-m', 'light', '-c']


default:
  @just -g --choose


nix-hm update='true':
  nh home switch {{ if update == "true" {"--update"} else {""} }} -c moi@bon  -- --impure

nix-os update='true':
  nh os switch {{ if update == "true" {"--update"} else {""} }}

nix-diff-os:
  # log profile dates
  ls -l /nix/var/nix/profiles/system-*-link/|tail -2
  nix store diff-closures $(ls -dv /nix/var/nix/profiles/system-*-link/|tail -2)


netd-restart:
  #!/usr/bin/env nu
  sudo systemctl stop strongswan-swanctl
  sudo systemctl restart systemd-networkd dnscrypt-proxy2 iwd
  systemctl is-active systemd-networkd dnscrypt-proxy2 iwd strongswan-swanctl


netd-journal:
  journalctl --since "12 hours ago" -u systemd-networkd -u dnscrypt-proxy2 -u iwd

gc:
  podman system prune --all --force && podman rmi --all --force
  nix-collect-garbage -d


scan out:
  systemctl restart avahi-daemon.service
  # scanadf -L
  scan --verbose --mode Color --resolution 600 -e 1 --no-default-size \
    -x 'airscan:e0:Canon TS5000 series' \
    --unpaper --ocr \
    -o {{out}}.pdf


updatecli:
  @just --justfile $DOT/dotfiles/dot_config/updatecli/justfile -d $DOT/dotfiles/dot_config/updatecli apply

grm:
  chezmoi apply -v -r $HOME/.config/git-repo-manager/config.yaml
  grm repos sync config --config ~/.config/git-repo-manager/config.yaml


klog:
  @just --choose --justfile $DOT/docs/wrk/timelog/justfile
