set $menu rofi -show drun -theme main-no-prompt
set $menu-reload-cache rofi -drun-reload-desktop-cache -show drun
set $menu-advanced rofi -show calc -modi calc -no-show-match -no-sort -theme spotlight-dark
set $term 'wezterm start --always-new-process'


bindsym $mod+Shift+q kill

### sway

bindsym $mod+Return exec $term
bindsym $mod+d exec $menu
bindsym $mod+shift+d exec $menu-reload-cache

bindsym $mod+left focus left
bindsym $mod+down focus down
bindsym $mod+up focus up
bindsym $mod+right focus right

# move focused window
bindsym $mod+shift+left move left
bindsym $mod+shift+down move down
bindsym $mod+shift+up move up
bindsym $mod+shift+right move right


bindsym $mod+h split h
bindsym $mod+v split v
bindsym $mod+f fullscreen toggle


bindsym $mod+s layout stacking
bindsym $mod+w layout tabbed
bindsym $mod+e layout toggle split

# toggle tiling / floating
bindsym $mod+Shift+space floating toggle

# change focus between tiling / floating windows
bindsym $mod+space focus mode_toggle

# focus the parent container
bindsym $mod+a focus parent

bindsym $mod+1 workspace 1
bindsym $mod+2 workspace 2
bindsym $mod+3 workspace 3
bindsym $mod+4 workspace 4
bindsym $mod+5 workspace 5
bindsym $mod+6 workspace 6
bindsym $mod+7 workspace 7
bindsym $mod+8 workspace 8
bindsym $mod+9 workspace 9
bindsym $mod+0 workspace 10

bindsym $mod+Shift+1 move container to workspace 1
bindsym $mod+Shift+2 move container to workspace 2
bindsym $mod+Shift+3 move container to workspace 3
bindsym $mod+Shift+4 move container to workspace 4
bindsym $mod+Shift+5 move container to workspace 5
bindsym $mod+Shift+6 move container to workspace 6
bindsym $mod+Shift+7 move container to workspace 7
bindsym $mod+Shift+8 move container to workspace 8
bindsym $mod+Shift+9 move container to workspace 9
bindsym $mod+Shift+0 move container to workspace 10

bindsym $mod+Control+Shift+left move workspace to output left
bindsym $mod+Control+Shift+down move workspace to output down
bindsym $mod+Control+Shift+up move workspace to output up
bindsym $mod+Control+Shift+right move workspace to output right

bindsym $mod+Shift+c reload
bindsym $mod+Shift+r restart
bindsym $mod+Control+Shift+e exec "swaynag -t warning -m 'Exit?' -b 'Mais oui!' 'swaymsg exit'"



### volume
bindsym --locked $mod+F1 exec "wpctl-wob toggle-mute"
bindsym $mod+F2 exec "wpctl-wob decrease-volume"
bindsym $mod+F2+Control exec "pavucontrol"
bindsym $mod+F3 exec "wpctl-wob increase-volume"

### mute mic
bindsym $mod+F4 exec "wpctl-wob toggle-mic-mute"

### light

# for external monitor: `modprobe ddcci; brightnessctl -d ddcci0 set 5%-`
bindsym --locked $mod+F5 exec "brightnessctl -m set 0%"
bindsym --locked $mod+F6 exec "brightnessctl -m set 100%"
bindsym $mod+F5+Control exec "brightnessctl -m set 5%- | choose -f ',|%' 3 > $WOBSOCK"
bindsym $mod+F6+Control exec "brightnessctl -m set +5% | choose -f ',|%' 3 > $WOBSOCK"

bindsym $mod+F7 exec "light -s sysfs/leds/tpacpi::kbd_backlight -S 0"
bindsym $mod+F8 exec "light -s sysfs/leds/tpacpi::kbd_backlight -S 100"



### utils

bindsym $mod+Control+e exec "wl-paste | xargs handlr open"
bindsym --release $mod+Home exec grim -g "$(slurp -o -r -c '#ff0000ff'; sleep 2)" - | satty --filename - --fullscreen --output-filename /tmp/satty-$(date '+%Y%m%d-%H:%M:%S').png
bindsym $mod+p exec "tessen"

bindsym $mod+Control+z exec "cliphist list | rofi -dmenu - 5 | cliphist decode | wl-copy"

bindsym $mod+Prior exec "esplanade"
